### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by castelao** [lnferris/ocean_data_tools#34]
This issue is part of the JOSS review ([openjournals/joss-reviews#2497](https://github.com/openjournals/joss-reviews/issues/2497))

Required. @kakearney made some good comments on the documentation #26, #28 & #29, and I think that those should not be simply suggestions, but should be addressed for the JOSS publication.

There is already a lot of information, but I found the documentation a little confusing. My first academic code packages were quite visionary (I think) but almost no one used because of my poor documentation at that time. There is really no limit on how much time we can invest in the documentation, but I think this is your best chance to create a good core. It will be hard to make time for that later. I reinforce the suggestion from @kakearney to improve the installation procedure, otherwise people get frustrated and give up without even trying your package. Experienced users probably already have their own system to fetch data. I think that a good fraction of your future users will be people learning, so abuse of clear and complete information, step by step.

Suggestion: Have you considered using the wiki resource from Github? It might be a convenient way to organize and maintain your documentation. It should be easy to move from /docs into the wiki, and you can clone the wiki itself. This is your call, I'm fine if you would rather use the current /docs. As your package evolves your README will turn into a huge file.

Another suggestion, I usually prefer a clean README with essential information about the package. If someone lands here, it should have just information enough to decide, "I'm the right place, let me learn more about this. Where are the examples?", or "this is not for me, let me keep searching for what I need".

**Comment by lnferris** [comment]
I have addressed #26 and am currently addressing #29. #28 is probably the only of your many helpful suggestions that I am going to push back on. The reason is that this is intended to be a living project, and I think it will be complicated to have to change the documentation in 3 places (embedded in functions, markdown, html) every time contributor someone adds or tweaks a function. I want contributing to be as accessible as possible and don't want to add a redundant place where documentation has to be changed/expanded every time this happens. 

Chad Greene (who was initially reviewing this) opened an issue requiring more documentation and suggested it could take the form of either a documentation page accessible in the Matlab Documentation Viewer or it could just detailed in the README.md. I addressed this by implementing linked Markdown files within the GitHub ecosystem, which I prefer to the Matlab ecosystem because it can more easily be expanded to documentation of shell scripts, python, etc.

**Comment by kthyng** [comment]
> it will be complicated to have to change the documentation in 3 places (embedded in functions, markdown, html) every time contributor someone adds or tweaks a function. I want contributing to be as accessible as possible and don't want to add a redundant place where documentation has to be changed/expanded every time this happens.

I am not familiar with the Matlab documentation discussed in #28, but generally speaking, all functions should have their own documentation which changes if that particular function changes. 

I am guessing that the markdown and html subsequently mentioned is for more of a narrative documentation. Presumably there is a way to create the html pages from the markdown pages, so there wouldn't be a need to update both independently.

We should have @kakearney here too since this is related to another issue.

**Comment by lnferris** [comment]
I have implemented documentation accessible in the Matlab Documentation Viewer https://github.com/lnferris/ocean_data_tools/issues/28.
